apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gpr0aadkc-nodejs 
  janus-idp.io/tekton: gpr0aadkc-nodejs
  backstage.io/kubernetes-id: gpr0aadkc-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gpr0aadkc-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml